server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    password: example
    username: postgres
users:
  list:
    - name: service.admin
      password: admin-pwd
      role: ADMIN
    - name: joona.norhausen
      password: password
      role: USER
